# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Log_In(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(371, 197)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TextLabel = QtWidgets.QLabel(self.centralwidget)
        self.TextLabel.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.TextLabel.setObjectName("TextLabel")
        self.input_id = QtWidgets.QTextEdit(self.centralwidget)
        self.input_id.setGeometry(QtCore.QRect(120, 10, 231, 31))
        self.input_id.setObjectName("input_id")
        self.TextLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.TextLabel_2.setGeometry(QtCore.QRect(10, 50, 100, 20))
        self.TextLabel_2.setObjectName("TextLabel_2")
        self.input_pwd = QtWidgets.QTextEdit(self.centralwidget)
        self.input_pwd.setGeometry(QtCore.QRect(120, 50, 231, 31))
        self.input_pwd.setObjectName("input_pwd")
        self.log_in = QtWidgets.QPushButton(self.centralwidget)
        self.log_in.setGeometry(QtCore.QRect(150, 100, 89, 25))
        self.log_in.setObjectName("log_in")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TextLabel.setText(_translate("MainWindow", "ID"))
        self.TextLabel_2.setText(_translate("MainWindow", "PassWD"))
        self.log_in.setText(_translate("MainWindow", "submit"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_Log_In()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

