# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mtr_ctrl.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mtr_Ctrl(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(267, 132)
        self.mtr_on_btn = QtWidgets.QPushButton(Dialog)
        self.mtr_on_btn.setGeometry(QtCore.QRect(20, 40, 101, 31))
        self.mtr_on_btn.setObjectName("mtr_on_btn")
        self.mtr_off_btn = QtWidgets.QPushButton(Dialog)
        self.mtr_off_btn.setGeometry(QtCore.QRect(140, 40, 101, 31))
        self.mtr_off_btn.setObjectName("mtr_off_btn")
        self.len_set_bar = QtWidgets.QSlider(Dialog)
        self.len_set_bar.setGeometry(QtCore.QRect(80, 100, 161, 20))
        self.len_set_bar.setOrientation(QtCore.Qt.Horizontal)
        self.len_set_bar.setObjectName("len_set_bar")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 151, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(150, 110, 111, 20))
        self.label_2.setObjectName("label_2")
        self.len_show = QtWidgets.QLabel(Dialog)
        self.len_show.setGeometry(QtCore.QRect(20, 80, 1000, 17))
        self.len_show.setObjectName("len_show")
        self.chk_inf = QtWidgets.QCheckBox(Dialog)
        self.chk_inf.setGeometry(QtCore.QRect(30, 100, 60, 23))
        self.chk_inf.setObjectName("chk_inf")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        print(self.len_set_bar.isEnabled())

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mtr_on_btn.setText(_translate("Dialog", "on"))
        self.mtr_off_btn.setText(_translate("Dialog", "off"))
        self.label.setText(_translate("Dialog", "moter control"))
        self.label_2.setText(_translate("Dialog", "max = 1090mm"))
        self.len_show.setText(_translate("Dialog", "TextLabel"))
        self.chk_inf.setText(_translate("Dialog", "inf"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Mtr_Ctrl()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())