# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yolov8_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yolo_view(object):
    def setupUi(self, Yolo_view):
        Yolo_view.setObjectName("Yolo_view")
        Yolo_view.resize(850, 500)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Yolo_view)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TextLabel = QtWidgets.QLabel(Yolo_view)
        self.TextLabel.setObjectName("TextLabel")
        self.verticalLayout_2.addWidget(self.TextLabel)
        self.original_img = QtWidgets.QGraphicsView(Yolo_view)
        self.original_img.setObjectName("original_img")
        self.verticalLayout_2.addWidget(self.original_img)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.TextLabel_2 = QtWidgets.QLabel(Yolo_view)
        self.TextLabel_2.setObjectName("TextLabel_2")
        self.verticalLayout.addWidget(self.TextLabel_2)
        self.yolo_img = QtWidgets.QGraphicsView(Yolo_view)
        self.yolo_img.setObjectName("yolo_img")
        self.verticalLayout.addWidget(self.yolo_img)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Yolo_view)
        QtCore.QMetaObject.connectSlotsByName(Yolo_view)

    def retranslateUi(self, Yolo_view):
        _translate = QtCore.QCoreApplication.translate
        Yolo_view.setWindowTitle(_translate("Yolo_view", "YoloV8 VIEW"))
        self.TextLabel.setText(_translate("Yolo_view", "ORIGINAL VIEW"))
        self.TextLabel_2.setText(_translate("Yolo_view", "YoloV8 VIEW"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Yolo_view = QtWidgets.QWidget()
#     ui = Ui_Yolo_view()
#     ui.setupUi(Yolo_view)
#     Yolo_view.show()
#     sys.exit(app.exec_())

